export interface VideoFormat {
  id: string;
  name: string;
  pillars: string[];
  platforms: string[];
  avg_engagement_note: string;
  hook_patterns: string[];
  structure_template: string[];
  best_for: string;
  production_difficulty: 'easy' | 'medium' | 'hard';
}

export const FORMAT_LIBRARY: VideoFormat[] = [
  {
    id: 'fmt_001',
    name: 'Talking-head seller education',
    pillars: ['seller education'],
    platforms: ['Instagram', 'TikTok', 'YouTube Shorts'],
    avg_engagement_note: '5.8% avg engagement — strongest seller lead driver',
    hook_patterns: [
      'Most sellers lose money before they even list.',
      'The mistake that cost this seller €20,000.',
      'If you\'re thinking of selling in {city}, watch this first.',
      '{N} things your agent won\'t tell you before you sign.',
    ],
    structure_template: [
      'Hook — provocative stat or mistake',
      'Problem setup — why this matters to sellers right now',
      'Point 1 with specific example',
      'Point 2 with specific example',
      'Point 3 (optional)',
      'Reframe — how to avoid the problem',
      'CTA — book a free valuation / DM for advice',
    ],
    best_for: 'Generating seller consultation requests from homeowners considering selling',
    production_difficulty: 'easy',
  },
  {
    id: 'fmt_002',
    name: 'Neighborhood walking tour',
    pillars: ['local authority'],
    platforms: ['Instagram', 'YouTube Shorts'],
    avg_engagement_note: '6.1% avg engagement — top save rate format for local authority',
    hook_patterns: [
      'Everyone knows {landmark}. But these streets are where people actually want to live.',
      'I\'ve sold in {neighbourhood} for {N} years — here\'s what nobody shows you.',
      'The hidden side of {neighbourhood} that buyers miss.',
      'Moving to {city}? Skip the tourist map. Walk here instead.',
    ],
    structure_template: [
      'Hook walking shot — agent on location, intrigue tease',
      'Location 1 — specific street or spot with local insight',
      'Location 2 — market, café, school or park with practical detail',
      'Location 3 — underrated gem or price context',
      'Agent insight — why this neighbourhood has long-term value',
      'CTA — follow for local guides / DM for neighbourhood report',
    ],
    best_for: 'Building hyper-local authority; highly shareable among people considering the area',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_003',
    name: 'Lifestyle listing tour',
    pillars: ['listing content'],
    platforms: ['Instagram', 'TikTok', 'YouTube Shorts'],
    avg_engagement_note: '4.9% avg engagement — highest direct inquiry conversion',
    hook_patterns: [
      'A {feature} in {city} — this rarely comes up.',
      'POV: you just moved into this {N}-bed in {neighbourhood}.',
      'This apartment has something almost impossible to find in the {arrondissement}.',
      '{Feature} reveal — the thing buyers always ask about.',
    ],
    structure_template: [
      'Hook — lead with the standout feature, not the address',
      'Feature reveal — the "wow" moment (terrace, view, courtyard)',
      'Living space walk-through — light and flow',
      'Kitchen and storage',
      'Bedrooms',
      'Location context — 30-second neighbourhood pull',
      'CTA — DM to book private viewing / link in bio',
    ],
    best_for: 'Generating direct viewing requests; also signals to sellers the quality of your marketing',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_004',
    name: 'Market update talking-head',
    pillars: ['educational', 'seller education'],
    platforms: ['Instagram', 'LinkedIn', 'YouTube Shorts'],
    avg_engagement_note: '5.2% avg engagement — strong save and share rate',
    hook_patterns: [
      'Here\'s what is actually happening in {city} real estate right now.',
      'Prices in {neighbourhood} just did something unexpected.',
      'The {month} market update every {city} seller needs to see.',
      'I track every sale in {neighbourhood}. Here is what I\'m seeing.',
    ],
    structure_template: [
      'Hook — bold market claim or surprising data point',
      'Context — where the market was 3–6 months ago',
      'Current data — price per sqm, volume, days on market',
      'What it means for sellers',
      'What it means for buyers',
      'Agent take — specific recommendation',
      'CTA — follow for monthly updates / book a call',
    ],
    best_for: 'Establishing market expertise; attracts sellers who are researching before listing',
    production_difficulty: 'easy',
  },
  {
    id: 'fmt_005',
    name: 'Client success story',
    pillars: ['trust building'],
    platforms: ['Instagram', 'LinkedIn'],
    avg_engagement_note: '4.4% avg engagement — highest comment rate; drives DMs from warm leads',
    hook_patterns: [
      'They had been searching for {N} months. We found their apartment in {N} weeks.',
      'We listed on a Tuesday. Sold by the weekend.',
      'This seller turned down an offer. It cost them €{N},000. Here\'s what happened.',
      '{Client first name} wanted to sell without an agent. Then this happened.',
    ],
    structure_template: [
      'Hook — the outcome, stated boldly',
      'Client situation — who they were and what they needed',
      'The challenge — what made it hard',
      'Our process — 2–3 specific things we did differently',
      'The result — numbers, timeline, outcome',
      'Client quote or reaction (if available)',
      'CTA — want the same result? Book a free consult',
    ],
    best_for: 'Converting warm leads who are comparing agents; works well as retargeting creative',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_006',
    name: 'Property price comparison reel',
    pillars: ['buyer education', 'educational'],
    platforms: ['Instagram', 'TikTok'],
    avg_engagement_note: '5.5% avg engagement — very high share rate among buyers',
    hook_patterns: [
      'What €{N}k buys you in {neighbourhood} right now.',
      '{Neighbourhood A} vs {Neighbourhood B} — same budget, very different life.',
      '3 apartments. Same price. Which one would you choose?',
      'Here\'s what changed in 12 months in {city} real estate.',
    ],
    structure_template: [
      'Hook — price/location contrast tease',
      'Property A — photo/video + key stats (size, floor, features)',
      'Property B — same format',
      'Property C (optional)',
      'Agent insight — what explains the difference',
      'CTA — DM for a personalised shortlist / follow for weekly picks',
    ],
    best_for: 'High reach and saves among active buyers; positions agent as market insider',
    production_difficulty: 'easy',
  },
  {
    id: 'fmt_007',
    name: 'Behind-the-scenes preparation vlog',
    pillars: ['trust building'],
    platforms: ['Instagram', 'TikTok'],
    avg_engagement_note: '4.7% avg engagement — strong for brand differentiation',
    hook_patterns: [
      'Most sellers never see what happens before the first viewing.',
      'Here\'s how we prepare a property for sale in 48 hours.',
      'What a €{N}k sale looks like behind the scenes.',
      'This is what separates a good agent from a great one.',
    ],
    structure_template: [
      'Hook — promise of insider access',
      'Scene 1 — staging or declutter walk-through',
      'Scene 2 — photography or video setup',
      'Scene 3 — listing copy or digital marketing prep',
      'Before/after reveal (if possible)',
      'CTA — want this for your property? DM us',
    ],
    best_for: 'Differentiating from cheap-fee competitors; strong seller lead generator among quality-conscious sellers',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_008',
    name: 'Local events & seasonal guide',
    pillars: ['local authority'],
    platforms: ['Instagram', 'YouTube Shorts'],
    avg_engagement_note: '5.9% avg engagement — highest reach during event periods',
    hook_patterns: [
      'This {month} in {neighbourhood} — everything happening near you.',
      'The {season} guide to {neighbourhood} nobody has made yet.',
      '{N} things to do in {neighbourhood} this weekend.',
      'Summer in {neighbourhood} hits different when you know these spots.',
    ],
    structure_template: [
      'Hook — seasonal energy or FOMO angle',
      'Event or activity 1 — specific name, date, location',
      'Event or activity 2',
      'Event or activity 3',
      'Local tip — insider knowledge only a resident would know',
      'Agent connection — "this is why people move here and stay"',
      'CTA — save this / follow for monthly local guides',
    ],
    best_for: 'Maximising reach and saves among locals and people researching the area; peaks around events',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_009',
    name: 'Opinion / authority take',
    pillars: ['local authority', 'seller education'],
    platforms: ['Instagram', 'TikTok', 'LinkedIn'],
    avg_engagement_note: '5.3% avg engagement — strong comment and share driver',
    hook_patterns: [
      'I\'ve worked in {neighbourhood} for {N} years. Here\'s my honest take.',
      'Hot take: {neighbourhood} is still the best bet for {audience} in {year}.',
      'Everyone says {common belief}. Here\'s why I disagree.',
      'The one thing I tell every client before they buy in {city}.',
    ],
    structure_template: [
      'Hook — confident, slightly controversial opening',
      'The belief — what most people think or say',
      'The reframe — agent\'s actual position with reasoning',
      'Evidence — 2–3 specific data points or personal examples',
      'Implication — what this means for buyers or sellers right now',
      'CTA — agree or disagree? DM me / follow for more takes',
    ],
    best_for: 'Building personal brand and thought leadership; attracts sellers who value expertise',
    production_difficulty: 'easy',
  },
  {
    id: 'fmt_010',
    name: 'Buyer education checklist',
    pillars: ['buyer education'],
    platforms: ['Instagram', 'TikTok'],
    avg_engagement_note: '4.8% avg engagement — very high save rate',
    hook_patterns: [
      '{N} questions to ask before signing anything.',
      'Most buyers find out too late. Save this before your next visit.',
      'What I wish someone had told me before buying in {city}.',
      'The checklist every first-time buyer needs in {country}.',
    ],
    structure_template: [
      'Hook — save-worthy promise',
      'Point 1 — specific, actionable tip',
      'Point 2',
      'Point 3',
      'Point 4 (optional)',
      'Summary — "get these right and you avoid 80% of buyer mistakes"',
      'CTA — save this / send to someone buying soon',
    ],
    best_for: 'High organic reach through shares; attracts buyer leads at research stage',
    production_difficulty: 'easy',
  },
  {
    id: 'fmt_011',
    name: 'Personal story / why I do this',
    pillars: ['trust building'],
    platforms: ['Instagram', 'LinkedIn'],
    avg_engagement_note: '4.2% avg engagement — highest emotional connection; drives referrals',
    hook_patterns: [
      'I could work anywhere in {city}. I chose {neighbourhood} — here\'s why.',
      'Nobody asks why I became a real estate agent. Here\'s the real answer.',
      '{N} years ago I made a promise to every client I work with.',
      'This is not just a job for me. Here\'s what it actually means.',
    ],
    structure_template: [
      'Hook — personal and specific opening',
      'The backstory — what led to this career or neighbourhood focus',
      'The moment — a specific experience that shaped the approach',
      'The commitment — what this means for every client',
      'Proof — a result or relationship that shows it',
      'CTA — work with someone who genuinely cares / DM to start a conversation',
    ],
    best_for: 'Humanising the brand; very strong for referral generation and long-term trust building',
    production_difficulty: 'easy',
  },
  {
    id: 'fmt_012',
    name: 'Feature-led listing tour',
    pillars: ['listing content'],
    platforms: ['Instagram', 'TikTok'],
    avg_engagement_note: '5.1% avg engagement — better reach than lifestyle tour when feature is rare',
    hook_patterns: [
      'Rooftop terrace in {neighbourhood} — this almost never comes up.',
      'A {feature} in a {city} apartment at this price? Let me show you.',
      'The thing that sold this apartment in 3 days.',
      'Wait for the {room/feature} reveal.',
    ],
    structure_template: [
      'Hook — feature-first, hold the reveal',
      'Building / street approach — location context',
      'Entrance and common areas',
      'The feature reveal — the hero moment (terrace, view, unusual room)',
      'Rest of apartment — quick, punchy',
      'Price and availability',
      'CTA — DM to visit / link in bio for full details',
    ],
    best_for: 'High-engagement listing content when a specific rare feature anchors the hook',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_013',
    name: 'Neighbourhood school & family guide',
    pillars: ['local authority', 'buyer education'],
    platforms: ['Instagram', 'YouTube Shorts'],
    avg_engagement_note: '5.6% avg engagement — very high save rate among families',
    hook_patterns: [
      'Moving to {neighbourhood} with kids? Here\'s what no one tells you about schools.',
      'The family guide to {neighbourhood} — schools, parks, and the things that matter.',
      '{N} reasons {neighbourhood} is the best arrondissement for raising kids.',
      'I help families find homes in {neighbourhood}. Here\'s what they always ask first.',
    ],
    structure_template: [
      'Hook — family-specific promise',
      'Schools — specific names, catchment, waiting list reality',
      'Parks and outdoor space',
      'After-school activities or sports infrastructure',
      'Safety and community feel — agent personal take',
      'Price reality — what family-sized apartments cost here',
      'CTA — DM for a personalised family relocation guide',
    ],
    best_for: 'Attracting family buyers and positioning as the go-to neighbourhood specialist',
    production_difficulty: 'medium',
  },
  {
    id: 'fmt_014',
    name: 'Investment case talking-head',
    pillars: ['educational', 'buyer education'],
    platforms: ['Instagram', 'LinkedIn', 'YouTube Shorts'],
    avg_engagement_note: '4.6% avg engagement — strong among investor audience on LinkedIn',
    hook_patterns: [
      'Here\'s why {neighbourhood} is still one of the best buys in {city}.',
      'The {city} neighbourhoods with the best rental yield right now.',
      'What a €{N}k investment property looks like in {city} in {year}.',
      'I track every investor deal in {neighbourhood}. Here\'s what I\'m seeing.',
    ],
    structure_template: [
      'Hook — investment angle, specific claim',
      'Market context — supply/demand dynamics',
      'Yield data — realistic rental income vs purchase price',
      'Price trend — 3-year trajectory in the area',
      'Risks — honest about downsides (credibility builder)',
      'Agent take — where the best value is right now',
      'CTA — DM for an investor shortlist / book a strategy call',
    ],
    best_for: 'Attracting investor buyers; strong on LinkedIn; positions agent as data-driven',
    production_difficulty: 'easy',
  },
];

export function getFormatById(id: string): VideoFormat | undefined {
  return FORMAT_LIBRARY.find(f => f.id === id);
}

export function getFormatsByPillar(pillar: string): VideoFormat[] {
  return FORMAT_LIBRARY.filter(f => f.pillars.includes(pillar));
}
